blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('about/',views.about, name='about'),
    path('contact/',views.contact, name='contact'),
    path('contact/post/',views.post_contact, name='post_contact'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('archives/<int:year>/<int:month>', views.ArchivesView.as_view(), name='archives'),
    path('categories/<int:pk>', views.CategoryView.as_view(), name='categories'),
    path('tags/<int:pk>', views.TagView.as_view(), name='tags'),
    path('search/', views.search, name='search'),
]

# app_name = 'blog'

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.feeds import AllPostRssFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('all/rss/', AllPostRssFeed(), name='rss'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-pk']

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=70)
    content = models.TextField()
    excerpt = models.CharField(max_length=200, blank=True)
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return f"/post/{self.id}/"
        return reverse('post-detail', kwargs={'pk':self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite'
            ])
            self.excerpt = strip_tags(md.convert(self.content))[:54]

        super(Post, self).save(*args, **kwargs)

    class Meta:
         ordering=['-created_time']

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.name

blog/forms.py
from django.forms import ModelForm
from .models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category, Tag
from .forms import ContactForm
import markdown
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 4

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args , **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):

        post = super().get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])
        post.content = md.convert(post.content)
        post.toc = md.toc
        return post

class ArchivesView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year, created_time__month=month)

class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk = self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)

class TagView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk = self.kwargs.get('pk'))
        return super().get_queryset().filter(tags=tag)

def about(request):
    return render(request, 'blog/about.html')

def post_contact(request):
    form = ContactForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return render(request,'blog/post_contact.html')
        else:
            return render(request, 'blog/contact.html',{'form': form})
    return render(request, 'blog/contact.html')

def contact(request):
    form = ContactForm()
    return render(request, 'blog/contact.html', {'form': form})

def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = '请输入关键词'
        return render(request, 'blog/index.html', {'error_msg':error_msg})

    post_list = Post.objects.filter(Q(title__icontains = q )|Q(content__icontains=q))
    return render(request, 'blog/index.html', {'error_msg':error_msg,'post_list':post_list})

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}
<html>
<head>
    <title>Hervie</title>

    <link rel="icon" href="{% static 'blog/img/favicon.ico' %}">
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'index' %}"><b>Hervie</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'contact' %}" data-hovr="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章！
                        {% endfor %}

                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_lists %}
                    <ul>
                        {% for date in date_lists %}
                        <li>
                            <a href="{% url 'archives' date.year date.month %}">{{ date.year }}年{{ date.month }}月</a>
                        </li>
                        {% empty %}
                        暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list%}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'categories' category.pk %}">{{ category.name }}<span class="post-count">({{ category.num_posts }})</span></a>
                        </li>
                        {% empty %}
                        暂无分类！
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% get_tags as tag_list %}
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'tags' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                            暂无标签！
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'index' %}">首页</a></li>
            <!--<li><a href="{% url 'index' %}">博客</a></li>-->
            <li><a href="{% url 'about' %}">关于</a></li>
            <li><a href="{% url 'contact' %}">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

templates/blog/about.html
{% extends 'base.html' %}

{% block main %}
<div class="entry-content clearfix">
<h3 align="center"><i>About Me</i></h3>
    <p>I'm Hervie.</p>
    <p>I'm a junior now.</p>
    <P>I'm a suny boy who loves life and is optimistic.</P>
    <p>I majored in Computer Science And Technology.</p>
    <p>All my efforts are to achieve a better myself.</p>
    <a href="https://github.com/vitalitywang">Github</a>
</div>
{% endblock %}

templates/blog/contact.html
{% extends 'base.html' %}
{% block main %}
<article class="post">
	<div class="entry-content clearfix">
		<form action="{% url 'post_contact' %}" method="post" class="contact-form">
			{% csrf_token %}
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
                    <label for="{{ form.name.id_for_lable }}">名字：</label>
					{{ form.name }}
					{{ form.name.errors }}
                    <label for="{{ form.email.id_for_lable }}">邮箱：</label>
					{{ form.email }}
					{{ form.email.errors }}
                    <label for="{{ form.subject.id_for_lable }}">主题：</label>
					{{ form.subject }}
					{{ form.subject.errors }}
                    <label for="{{ form.message.id_for_lable }}">内容：</label>
					{{ form.message }}
					{{ form.message.errors }}
					<button class="btn-send btn-5 btn-5b ion-ios-paperplane" type="submit"><span>提交</span></button>
				</div>
			</div>	<!-- row -->
		</form>
	</div>
</article>
{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}}
{% block main %}
<article class="post post-1">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.user }}</a></span>
            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{ post.content|safe }}
    </div>
    <ul>
        {% for tag in post.tag.all %}
        <li>{{ tag.name }}</li>
        {% endfor %}
    </ul>
</article>
{% endblock main %}

{% block toc %}
<div class="widget widget-content">
    <h3 class="widget-title">文章目录</h3>
    <ul>
        <li>
            <a href="#">{{ post.toc|safe }}</a>
        </li>
    </ul>
</div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
    {% if error_msg %}
    <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.user }}</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}...</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                <div class="no-post">暂时还没有发布文章！</div>
                {% endfor %}

<!--简单分页效果-->
{% if is_paginated %}
<div class="pagination-simple">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
    {% endif %}
    <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
    {% endif %}
</div>
{% endif %}
{% endblock main %}

templates/blog/post_contact.html
{% extends 'base.html' %}

{% block main %}
<p align="center">提交成功</p>
{% endblock main %}